# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Execute Python script daily

on:
  schedule:
    - cron: '55 09 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11  # Remplacez "x" par la version de Python que vous utilisez

    - name: Install dependencies
      run: pip install -r rep/test/requirements.txt  # Si vous avez un fichier requirements.txt pour les dépendances

    
        
    - name: Run Python script
      working-directory: lvoro/test
      run: python stockage_datas_hydro.py
