name: Daily Python Script

on:
  schedule:
    - cron: '0 18 * * *' # Execute every day at 18:00

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Python script
      run: python hydro_max_jour.py

    - name: Rename CSV file
      run: mv output.csv "$(date +'%m-%Y').csv"

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update CSV file"
        git push












































































